#!/bin/bash

echo "🚀 Deploying NumPy 2.x Fix to Ubuntu Server"
echo "=========================================="

# Files that need to be uploaded to Ubuntu server
echo "📁 Files to upload to /opt/bb-screener/:"
echo "  ✅ numpy_patch.py (NEW - aggressive global fix)"
echo "  ✅ main_scanner.py (MODIFIED - ultra-aggressive patch)"
echo "  ✅ run_scanner.py (NEW - wrapper script)"
echo "  ✅ test_ubuntu_fix.py (NEW - test script)"
echo ""
echo "📋 Commands to run on Ubuntu server:"
echo ""
echo "1. Upload files:"
echo "   scp numpy_patch.py main_scanner.py run_scanner.py test_ubuntu_fix.py root@your-server:/opt/bb-screener/"
echo ""
echo "2. Test the fix:"
echo "   cd /opt/bb-screener"
echo "   python3 test_ubuntu_fix.py"
echo ""
echo "3. If test passes, run the scanner using the wrapper:"
echo "   python3 run_scanner.py"
echo ""
echo "4. Or run directly (if you prefer):"
echo "   python3 main_scanner.py"
echo ""
echo "🔧 What this fix does:"
echo "- Ultra-aggressive NumPy patching at startup"
echo "- Patches NumPy module before ANY other imports"
echo "- Works with NumPy 2.3.1 on Ubuntu"
echo "- Handles all dependencies that might import NaN"
echo "- Provides wrapper script for guaranteed compatibility"
echo ""
echo "✅ Ready for deployment!" 