#!/bin/bash

echo "🚀 Deploying NumPy 2.x Fix to Ubuntu Server"
echo "=========================================="

# Files that need to be uploaded to Ubuntu server
echo "📁 Files to upload to /opt/bb-screener/:"
echo "  ✅ numpy_patch.py (NEW - aggressive global fix)"
echo "  ✅ main_scanner.py (MODIFIED - imports patch first)"
echo "  ✅ test_ubuntu_fix.py (NEW - test script)"
echo ""
echo "📋 Commands to run on Ubuntu server:"
echo ""
echo "1. Upload files:"
echo "   scp numpy_patch.py main_scanner.py test_ubuntu_fix.py root@your-server:/opt/bb-screener/"
echo ""
echo "2. Test the fix:"
echo "   cd /opt/bb-screener"
echo "   python3 test_ubuntu_fix.py"
echo ""
echo "3. If test passes, run the scanner:"
echo "   python3 main_scanner.py"
echo ""
echo "🔧 What this fix does:"
echo "- Aggressively patches NumPy module before any imports"
echo "- Makes NaN available in numpy.__dict__ and numpy.__all__"
echo "- Works with NumPy 2.3.1 on Ubuntu"
echo "- Handles all dependencies that might import NaN"
echo ""
echo "✅ Ready for deployment!" 