#!/bin/bash

echo "🚀 DEPLOYING BB SCREENER TO DIGITALOCEAN"
echo "========================================"

# Configuration
SERVER_IP="165.232.160.52"
SERVER_USER="root"
PROJECT_DIR="/opt/bb-screener"

echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1. ✅ Code pushed to GitHub (COMPLETED)"
echo "   - All NumPy fixes committed and pushed"
echo "   - Files ready: numpy_patch.py, run_scanner.py, test_ubuntu_fix.py"
echo ""
echo "2. 🔗 Connect to your DigitalOcean server:"
echo "   ssh root@165.232.160.52"
echo ""
echo "3. 📥 Pull the latest code:"
echo "   cd $PROJECT_DIR"
echo "   git pull origin master"
echo ""
echo "4. 🧪 Test the NumPy fix:"
echo "   python3 test_ubuntu_fix.py"
echo ""
echo "5. 🚀 Run the BB Scanner:"
echo "   python3 run_scanner.py"
echo ""
echo "📁 Files that should be present after git pull:"
echo "  ✅ numpy_patch.py"
echo "  ✅ run_scanner.py"
echo "  ✅ test_ubuntu_fix.py"
echo "  ✅ main_scanner.py (updated with NumPy fix)"
echo ""
echo "🔧 Troubleshooting Commands:"
echo ""
echo "If git pull fails:"
echo "  git status"
echo "  git stash"
echo "  git pull origin master"
echo ""
echo "If test fails:"
echo "  python3 -c \"import numpy; print('NumPy version:', numpy.__version__)\""
echo "  python3 -c \"import numpy_patch; print('Patch applied')\""
echo ""
echo "If scanner fails:"
echo "  python3 -c \"import main_scanner; print('Main scanner loads')\""
echo ""
echo "✅ Ready for DigitalOcean deployment!" 